[package]
name = "game"
version = "0.0.1"
authors = ["Gustav <sir.gustav.the.coder@gmail.com>"]

[dependencies]
sdl2 = "*"
glium = "*"
libc = "*"

# http://rust-ci.org/bjz/cgmath-rs/doc/cgmath/index.html
cgmath = "*"
